services:
  frontend:
    build: ./Techdome-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./Techdome-backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/mydb

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
